all:copy shell single multi
copy:copy.c
        g++ copy.c -o copy
shell:shell.c
        g++ shell.c -o shell
single:single.c
        g++ single.c -o single
multi:multi.c
        g++ multi.c -o multi
